# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/RVfpga_test/RVfpga_test.srcs/sources_1/bd/interconnect/ip/interconnect_axi_vip_0_0/interconnect_axi_vip_0_0.xci
# IP: The module: 'interconnect_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/RVfpga_test/RVfpga_test.gen/sources_1/bd/interconnect/ip/interconnect_axi_vip_0_0/interconnect_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/RVfpga_test/RVfpga_test.srcs/sources_1/bd/interconnect/ip/interconnect_axi_vip_0_0/interconnect_axi_vip_0_0.xci
# IP: The module: 'interconnect_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/RVfpga_test/RVfpga_test.gen/sources_1/bd/interconnect/ip/interconnect_axi_vip_0_0/interconnect_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
