# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect3S2M/rvfpga_interconnect3s2m/rvfpga_interconnect3s2m.srcs/sources_1/bd/interconnect3s2m/ip/interconnect3s2m_s01_data_fifo_0/interconnect3s2m_s01_data_fifo_0.xci
# IP: The module: 'interconnect3s2m_s01_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect3S2M/rvfpga_interconnect3s2m/rvfpga_interconnect3s2m.gen/sources_1/bd/interconnect3s2m/ip/interconnect3s2m_s01_data_fifo_0/interconnect3s2m_s01_data_fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect3s2m_s01_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect3S2M/rvfpga_interconnect3s2m/rvfpga_interconnect3s2m.gen/sources_1/bd/interconnect3s2m/ip/interconnect3s2m_s01_data_fifo_0/interconnect3s2m_s01_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect3s2m_s01_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect3S2M/rvfpga_interconnect3s2m/rvfpga_interconnect3s2m.srcs/sources_1/bd/interconnect3s2m/ip/interconnect3s2m_s01_data_fifo_0/interconnect3s2m_s01_data_fifo_0.xci
# IP: The module: 'interconnect3s2m_s01_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect3S2M/rvfpga_interconnect3s2m/rvfpga_interconnect3s2m.gen/sources_1/bd/interconnect3s2m/ip/interconnect3s2m_s01_data_fifo_0/interconnect3s2m_s01_data_fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect3s2m_s01_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect3S2M/rvfpga_interconnect3s2m/rvfpga_interconnect3s2m.gen/sources_1/bd/interconnect3s2m/ip/interconnect3s2m_s01_data_fifo_0/interconnect3s2m_s01_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect3s2m_s01_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
