-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matprod_matprod_Pipeline_VITIS_LOOP_26_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    N1 : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln6_1 : IN STD_LOGIC_VECTOR (9 downto 0);
    m1_buffer_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    m1_buffer_ce0 : OUT STD_LOGIC;
    m1_buffer_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    trunc_ln6 : IN STD_LOGIC_VECTOR (9 downto 0);
    m2_buffer_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    m2_buffer_ce0 : OUT STD_LOGIC;
    m2_buffer_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    N2 : IN STD_LOGIC_VECTOR (31 downto 0);
    m3_buffer_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    m3_buffer_ce0 : OUT STD_LOGIC;
    m3_buffer_we0 : OUT STD_LOGIC;
    m3_buffer_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    N3 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_202_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_202_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_202_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_202_p_ce : OUT STD_LOGIC );
end;


architecture behav of matprod_matprod_Pipeline_VITIS_LOOP_26_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln26_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal regc : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_2_reg_337 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln17_fu_154_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln17_reg_346 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln17_reg_346_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln17_1_fu_158_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln17_1_reg_352 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln17_1_reg_352_pp0_iter2_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln17_2_fu_162_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln30_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_364_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln33_reg_369_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_1_fu_188_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_1_reg_373 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln37_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_378 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln37_fu_199_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln37_reg_384 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_283_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln35_reg_399 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln35_reg_399_pp0_iter5_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln35_reg_399_pp0_iter6_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln35_reg_399_pp0_iter7_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal m1_buffer_load_reg_404 : STD_LOGIC_VECTOR (31 downto 0);
    signal m2_buffer_load_reg_409 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_414 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln29_fu_231_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln29_1_fu_235_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln35_fu_265_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln30_fu_252_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_fu_44 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_1_fu_172_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_48 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_2_fu_215_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_52 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_3_fu_210_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln29_fu_231_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_269_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln29_1_fu_235_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_276_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln31_fu_247_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_276_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matprod_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matprod_mac_muladd_10s_10s_10s_10_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component matprod_mac_muladd_10s_10s_10ns_10_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component matprod_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_10s_10s_10s_10_4_1_U10 : component matprod_mac_muladd_10s_10s_10s_10_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        din2_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln17_2_fu_162_p1,
        din1 => trunc_ln6_1,
        din2 => trunc_ln17_1_reg_352_pp0_iter2_reg,
        ce => ap_const_logic_1,
        dout => grp_fu_269_p3);

    mac_muladd_10s_10s_10ns_10_4_1_U11 : component matprod_mac_muladd_10s_10s_10ns_10_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        din2_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_276_p0,
        din1 => trunc_ln6,
        din2 => trunc_ln17_reg_346_pp0_iter2_reg,
        ce => ap_const_logic_1,
        dout => grp_fu_276_p3);

    mac_muladd_10s_10s_10ns_10_4_1_U12 : component matprod_mac_muladd_10s_10s_10ns_10_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        din2_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln17_2_fu_162_p1,
        din1 => trunc_ln6,
        din2 => trunc_ln17_reg_346_pp0_iter2_reg,
        ce => ap_const_logic_1,
        dout => grp_fu_283_p3);

    flow_control_loop_pipe_sequential_init_U : component matprod_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    i_fu_52_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    i_fu_52 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln33_reg_369 = ap_const_lv1_1))) then 
                    i_fu_52 <= i_3_fu_210_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    j_fu_48 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln33_reg_369 = ap_const_lv1_1))) then 
                    j_fu_48 <= j_2_fu_215_p3;
                end if;
            end if; 
        end if;
    end process;

    k_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln26_fu_143_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln33_fu_178_p2 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                k_fu_44 <= ap_const_lv32_0;
            elsif (((icmp_ln26_fu_143_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln33_fu_178_p2 = ap_const_lv1_0))) then 
                k_fu_44 <= k_1_fu_172_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln33_reg_369_pp0_iter3_reg = ap_const_lv1_1))) then
                add_ln35_reg_399 <= grp_fu_283_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln35_reg_399_pp0_iter5_reg <= add_ln35_reg_399;
                add_ln35_reg_399_pp0_iter6_reg <= add_ln35_reg_399_pp0_iter5_reg;
                add_ln35_reg_399_pp0_iter7_reg <= add_ln35_reg_399_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                icmp_ln30_reg_364_pp0_iter2_reg <= icmp_ln30_reg_364;
                icmp_ln30_reg_364_pp0_iter3_reg <= icmp_ln30_reg_364_pp0_iter2_reg;
                icmp_ln30_reg_364_pp0_iter4_reg <= icmp_ln30_reg_364_pp0_iter3_reg;
                icmp_ln30_reg_364_pp0_iter5_reg <= icmp_ln30_reg_364_pp0_iter4_reg;
                icmp_ln30_reg_364_pp0_iter6_reg <= icmp_ln30_reg_364_pp0_iter5_reg;
                icmp_ln30_reg_364_pp0_iter7_reg <= icmp_ln30_reg_364_pp0_iter6_reg;
                icmp_ln33_reg_369_pp0_iter2_reg <= icmp_ln33_reg_369;
                icmp_ln33_reg_369_pp0_iter3_reg <= icmp_ln33_reg_369_pp0_iter2_reg;
                icmp_ln33_reg_369_pp0_iter4_reg <= icmp_ln33_reg_369_pp0_iter3_reg;
                icmp_ln33_reg_369_pp0_iter5_reg <= icmp_ln33_reg_369_pp0_iter4_reg;
                icmp_ln33_reg_369_pp0_iter6_reg <= icmp_ln33_reg_369_pp0_iter5_reg;
                icmp_ln33_reg_369_pp0_iter7_reg <= icmp_ln33_reg_369_pp0_iter6_reg;
                m1_buffer_load_reg_404 <= m1_buffer_q0;
                m2_buffer_load_reg_409 <= m2_buffer_q0;
                mul_reg_414 <= grp_fu_202_p_dout0;
                trunc_ln17_1_reg_352_pp0_iter2_reg <= trunc_ln17_1_reg_352;
                trunc_ln17_reg_346_pp0_iter2_reg <= trunc_ln17_reg_346;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_143_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln33_fu_178_p2 = ap_const_lv1_1))) then
                add_ln37_reg_384 <= add_ln37_fu_199_p2;
                icmp_ln37_reg_378 <= icmp_ln37_fu_194_p2;
                j_1_reg_373 <= j_1_fu_188_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                i_2_reg_337 <= ap_sig_allocacmp_i_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_143_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln30_reg_364 <= icmp_ln30_fu_166_p2;
                icmp_ln33_reg_369 <= icmp_ln33_fu_178_p2;
                trunc_ln17_1_reg_352 <= trunc_ln17_1_fu_158_p1;
                trunc_ln17_reg_346 <= trunc_ln17_fu_154_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then
                regc <= select_ln30_fu_252_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln31_fu_247_p2 <= std_logic_vector(unsigned(regc) + unsigned(mul_reg_414));
    add_ln37_fu_199_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln26_fu_143_p2)
    begin
        if (((icmp_ln26_fu_143_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln33_reg_369, ap_block_pp0_stage0, i_fu_52, i_3_fu_210_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln33_reg_369 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_i_2 <= i_3_fu_210_p3;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_52;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln33_reg_369, ap_block_pp0_stage0, j_fu_48, j_2_fu_215_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln33_reg_369 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_j_load <= j_2_fu_215_p3;
        else 
            ap_sig_allocacmp_j_load <= j_fu_48;
        end if; 
    end process;

    grp_fu_202_p_ce <= ap_const_logic_1;
    grp_fu_202_p_din0 <= m2_buffer_load_reg_409;
    grp_fu_202_p_din1 <= m1_buffer_load_reg_404;
    grp_fu_276_p0 <= k_fu_44(10 - 1 downto 0);
    i_3_fu_210_p3 <= 
        add_ln37_reg_384 when (icmp_ln37_reg_378(0) = '1') else 
        i_2_reg_337;
    icmp_ln26_fu_143_p2 <= "1" when (signed(ap_sig_allocacmp_i_2) < signed(N1)) else "0";
    icmp_ln30_fu_166_p2 <= "1" when (k_fu_44 = ap_const_lv32_0) else "0";
    icmp_ln33_fu_178_p2 <= "1" when (k_1_fu_172_p2 = N2) else "0";
    icmp_ln37_fu_194_p2 <= "1" when (j_1_fu_188_p2 = N3) else "0";
    j_1_fu_188_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_load) + unsigned(ap_const_lv32_1));
    j_2_fu_215_p3 <= 
        ap_const_lv32_0 when (icmp_ln37_reg_378(0) = '1') else 
        j_1_reg_373;
    k_1_fu_172_p2 <= std_logic_vector(unsigned(k_fu_44) + unsigned(ap_const_lv32_1));
    m1_buffer_address0 <= zext_ln29_fu_231_p1(10 - 1 downto 0);

    m1_buffer_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            m1_buffer_ce0 <= ap_const_logic_1;
        else 
            m1_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m2_buffer_address0 <= zext_ln29_1_fu_235_p1(10 - 1 downto 0);

    m2_buffer_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            m2_buffer_ce0 <= ap_const_logic_1;
        else 
            m2_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m3_buffer_address0 <= zext_ln35_fu_265_p1(10 - 1 downto 0);

    m3_buffer_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            m3_buffer_ce0 <= ap_const_logic_1;
        else 
            m3_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m3_buffer_d0 <= 
        mul_reg_414 when (icmp_ln30_reg_364_pp0_iter7_reg(0) = '1') else 
        add_ln31_fu_247_p2;

    m3_buffer_we0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, icmp_ln33_reg_369_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln33_reg_369_pp0_iter7_reg = ap_const_lv1_1))) then 
            m3_buffer_we0 <= ap_const_logic_1;
        else 
            m3_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln30_fu_252_p3 <= 
        mul_reg_414 when (icmp_ln30_reg_364_pp0_iter7_reg(0) = '1') else 
        add_ln31_fu_247_p2;
    trunc_ln17_1_fu_158_p1 <= k_fu_44(10 - 1 downto 0);
    trunc_ln17_2_fu_162_p1 <= ap_sig_allocacmp_i_2(10 - 1 downto 0);
    trunc_ln17_fu_154_p1 <= ap_sig_allocacmp_j_load(10 - 1 downto 0);
    zext_ln29_1_fu_235_p0 <= grp_fu_276_p3;
    zext_ln29_1_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln29_1_fu_235_p0),64));
    zext_ln29_fu_231_p0 <= grp_fu_269_p3;
    zext_ln29_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln29_fu_231_p0),64));
    zext_ln35_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln35_reg_399_pp0_iter7_reg),64));
end behav;
