# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect/src/rvfpganexys.xdc

# XDC: C:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect/src/LiteDRAM/liteDRAM.xdc

# Block Designs: bd/axi_interconnect/axi_interconnect.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect || ORIG_REF_NAME==axi_interconnect} -quiet] -quiet

# IP: bd/axi_interconnect/ip/axi_interconnect_xbar_0/axi_interconnect_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect_xbar_0 || ORIG_REF_NAME==axi_interconnect_xbar_0} -quiet] -quiet

# IP: bd/axi_interconnect/ip/axi_interconnect_s00_data_fifo_0/axi_interconnect_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect_s00_data_fifo_0 || ORIG_REF_NAME==axi_interconnect_s00_data_fifo_0} -quiet] -quiet

# IP: bd/axi_interconnect/ip/axi_interconnect_s01_data_fifo_0/axi_interconnect_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect_s01_data_fifo_0 || ORIG_REF_NAME==axi_interconnect_s01_data_fifo_0} -quiet] -quiet

# IP: bd/axi_interconnect/ip/axi_interconnect_s02_data_fifo_0/axi_interconnect_s02_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect_s02_data_fifo_0 || ORIG_REF_NAME==axi_interconnect_s02_data_fifo_0} -quiet] -quiet

# IP: bd/axi_interconnect/ip/axi_interconnect_axi_interconnect_0_0/axi_interconnect_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_interconnect_axi_interconnect_0_0 || ORIG_REF_NAME==axi_interconnect_axi_interconnect_0_0} -quiet] -quiet

# XDC: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpgaInterconnect/rvfpga/rvfpga.gen/sources_1/bd/axi_interconnect/axi_interconnect_ooc.xdc
