// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matprod_matprod_Pipeline_VITIS_LOOP_26_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        N1,
        trunc_ln6_1,
        m1_buffer_address0,
        m1_buffer_ce0,
        m1_buffer_q0,
        trunc_ln6,
        m2_buffer_address0,
        m2_buffer_ce0,
        m2_buffer_q0,
        N2,
        m3_buffer_address0,
        m3_buffer_ce0,
        m3_buffer_we0,
        m3_buffer_d0,
        N3
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] N1;
input  [9:0] trunc_ln6_1;
output  [9:0] m1_buffer_address0;
output   m1_buffer_ce0;
input  [31:0] m1_buffer_q0;
input  [9:0] trunc_ln6;
output  [9:0] m2_buffer_address0;
output   m2_buffer_ce0;
input  [31:0] m2_buffer_q0;
input  [31:0] N2;
output  [9:0] m3_buffer_address0;
output   m3_buffer_ce0;
output   m3_buffer_we0;
output  [31:0] m3_buffer_d0;
input  [31:0] N3;

reg ap_idle;
reg m1_buffer_ce0;
reg m2_buffer_ce0;
reg m3_buffer_ce0;
reg m3_buffer_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_state9_pp0_stage2_iter2;
wire    ap_block_state12_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln26_reg_334;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] regc;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_state10_pp0_stage0_iter3;
wire    ap_block_state13_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln26_fu_145_p2;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_state8_pp0_stage1_iter2;
wire    ap_block_state11_pp0_stage1_iter3;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln26_reg_334_pp0_iter1_reg;
reg   [0:0] icmp_ln26_reg_334_pp0_iter2_reg;
wire   [9:0] empty_fu_156_p1;
reg   [9:0] empty_reg_338;
reg   [9:0] empty_reg_338_pp0_iter1_reg;
wire  signed [9:0] empty_20_fu_160_p1;
reg  signed [9:0] empty_20_reg_344;
wire  signed [9:0] empty_21_fu_164_p1;
reg  signed [9:0] empty_21_reg_350;
wire   [0:0] icmp_ln28_fu_168_p2;
reg   [0:0] icmp_ln28_reg_356;
reg   [0:0] icmp_ln28_reg_356_pp0_iter1_reg;
reg   [0:0] icmp_ln28_reg_356_pp0_iter2_reg;
reg   [0:0] icmp_ln28_reg_356_pp0_iter3_reg;
wire   [0:0] icmp_ln31_fu_180_p2;
reg   [0:0] icmp_ln31_reg_361;
reg   [0:0] icmp_ln31_reg_361_pp0_iter1_reg;
reg   [0:0] icmp_ln31_reg_361_pp0_iter2_reg;
reg   [0:0] icmp_ln31_reg_361_pp0_iter3_reg;
reg   [31:0] m1_buffer_load_reg_370;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] m2_buffer_load_reg_380;
wire   [9:0] grp_fu_281_p3;
reg  signed [9:0] add_ln33_reg_385;
reg  signed [9:0] add_ln33_reg_385_pp0_iter3_reg;
wire   [31:0] grp_fu_123_p2;
reg   [31:0] mul_reg_390;
reg   [31:0] mul_reg_390_pp0_iter3_reg;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln27_fu_238_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln27_1_fu_242_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln33_fu_264_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] select_ln28_fu_251_p3;
reg   [31:0] ap_sig_allocacmp_regc_load;
reg   [31:0] k_fu_38;
wire   [31:0] k_1_fu_174_p2;
wire    ap_loop_init;
reg   [31:0] j_fu_42;
wire   [31:0] j_2_fu_215_p3;
reg   [31:0] i_fu_46;
wire   [31:0] i_3_fu_207_p3;
wire   [31:0] j_1_fu_190_p2;
wire   [0:0] icmp_ln35_fu_196_p2;
wire   [31:0] add_ln35_fu_201_p2;
wire  signed [9:0] zext_ln27_fu_238_p0;
wire   [9:0] grp_fu_268_p3;
wire  signed [9:0] zext_ln27_1_fu_242_p0;
wire   [9:0] grp_fu_275_p3;
wire   [31:0] grp_fu_119_p2;
wire  signed [9:0] grp_fu_268_p0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
reg    ap_done_pending_pp0;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 regc = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

matprod_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_regc_load),
    .din1(mul_reg_390),
    .ce(1'b1),
    .dout(grp_fu_119_p2)
);

matprod_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m1_buffer_load_reg_370),
    .din1(m2_buffer_load_reg_380),
    .ce(1'b1),
    .dout(grp_fu_123_p2)
);

matprod_mac_muladd_10s_10s_10s_10_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mac_muladd_10s_10s_10s_10_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_268_p0),
    .din1(trunc_ln6_1),
    .din2(empty_20_reg_344),
    .ce(1'b1),
    .dout(grp_fu_268_p3)
);

matprod_mac_muladd_10s_10s_10ns_10_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mac_muladd_10s_10s_10ns_10_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_20_reg_344),
    .din1(trunc_ln6),
    .din2(empty_reg_338),
    .ce(1'b1),
    .dout(grp_fu_275_p3)
);

matprod_mac_muladd_10s_10s_10ns_10_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mac_muladd_10s_10s_10ns_10_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_21_reg_350),
    .din1(trunc_ln6),
    .din2(empty_reg_338_pp0_iter1_reg),
    .ce(1'b1),
    .dout(grp_fu_281_p3)
);

matprod_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_46 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln31_fu_180_p2 == 1'd1) & (icmp_ln26_fu_145_p2 == 1'd1))) begin
        i_fu_46 <= i_3_fu_207_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_42 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln31_fu_180_p2 == 1'd1) & (icmp_ln26_fu_145_p2 == 1'd1))) begin
        j_fu_42 <= j_2_fu_215_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln31_fu_180_p2 == 1'd1) & (icmp_ln26_fu_145_p2 == 1'd1)))) begin
        k_fu_38 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln31_fu_180_p2 == 1'd0) & (icmp_ln26_fu_145_p2 == 1'd1))) begin
        k_fu_38 <= k_1_fu_174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln31_reg_361_pp0_iter1_reg == 1'd1))) begin
        add_ln33_reg_385 <= grp_fu_281_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln33_reg_385_pp0_iter3_reg <= add_ln33_reg_385;
        m2_buffer_load_reg_380 <= m2_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln26_fu_145_p2 == 1'd1))) begin
        empty_20_reg_344 <= empty_20_fu_160_p1;
        empty_21_reg_350 <= empty_21_fu_164_p1;
        empty_reg_338 <= empty_fu_156_p1;
        icmp_ln28_reg_356 <= icmp_ln28_fu_168_p2;
        icmp_ln31_reg_361 <= icmp_ln31_fu_180_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_reg_338_pp0_iter1_reg <= empty_reg_338;
        icmp_ln26_reg_334 <= icmp_ln26_fu_145_p2;
        icmp_ln26_reg_334_pp0_iter1_reg <= icmp_ln26_reg_334;
        icmp_ln26_reg_334_pp0_iter2_reg <= icmp_ln26_reg_334_pp0_iter1_reg;
        icmp_ln28_reg_356_pp0_iter1_reg <= icmp_ln28_reg_356;
        icmp_ln28_reg_356_pp0_iter2_reg <= icmp_ln28_reg_356_pp0_iter1_reg;
        icmp_ln28_reg_356_pp0_iter3_reg <= icmp_ln28_reg_356_pp0_iter2_reg;
        icmp_ln31_reg_361_pp0_iter1_reg <= icmp_ln31_reg_361;
        icmp_ln31_reg_361_pp0_iter2_reg <= icmp_ln31_reg_361_pp0_iter1_reg;
        icmp_ln31_reg_361_pp0_iter3_reg <= icmp_ln31_reg_361_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        m1_buffer_load_reg_370 <= m1_buffer_q0;
        mul_reg_390 <= grp_fu_123_p2;
        mul_reg_390_pp0_iter3_reg <= mul_reg_390;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        regc <= select_ln28_fu_251_p3;
    end
end

always @ (*) begin
    if (((icmp_ln26_reg_334 == 1'd0) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln26_reg_334_pp0_iter2_reg == 1'd0))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_regc_load = select_ln28_fu_251_p3;
    end else begin
        ap_sig_allocacmp_regc_load = regc;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m1_buffer_ce0 = 1'b1;
    end else begin
        m1_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        m2_buffer_ce0 = 1'b1;
    end else begin
        m2_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m3_buffer_ce0 = 1'b1;
    end else begin
        m3_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln31_reg_361_pp0_iter3_reg == 1'd1))) begin
        m3_buffer_we0 = 1'b1;
    end else begin
        m3_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_201_p2 = (i_fu_46 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign empty_20_fu_160_p1 = k_fu_38[9:0];

assign empty_21_fu_164_p1 = i_fu_46[9:0];

assign empty_fu_156_p1 = j_fu_42[9:0];

assign grp_fu_268_p0 = i_fu_46[9:0];

assign i_3_fu_207_p3 = ((icmp_ln35_fu_196_p2[0:0] == 1'b1) ? add_ln35_fu_201_p2 : i_fu_46);

assign icmp_ln26_fu_145_p2 = (($signed(i_fu_46) < $signed(N1)) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_168_p2 = ((k_fu_38 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_180_p2 = ((k_1_fu_174_p2 == N2) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_196_p2 = ((j_1_fu_190_p2 == N3) ? 1'b1 : 1'b0);

assign j_1_fu_190_p2 = (j_fu_42 + 32'd1);

assign j_2_fu_215_p3 = ((icmp_ln35_fu_196_p2[0:0] == 1'b1) ? 32'd0 : j_1_fu_190_p2);

assign k_1_fu_174_p2 = (k_fu_38 + 32'd1);

assign m1_buffer_address0 = zext_ln27_fu_238_p1;

assign m2_buffer_address0 = zext_ln27_1_fu_242_p1;

assign m3_buffer_address0 = zext_ln33_fu_264_p1;

assign m3_buffer_d0 = ((icmp_ln28_reg_356_pp0_iter3_reg[0:0] == 1'b1) ? mul_reg_390_pp0_iter3_reg : grp_fu_119_p2);

assign select_ln28_fu_251_p3 = ((icmp_ln28_reg_356_pp0_iter3_reg[0:0] == 1'b1) ? mul_reg_390_pp0_iter3_reg : grp_fu_119_p2);

assign zext_ln27_1_fu_242_p0 = grp_fu_275_p3;

assign zext_ln27_1_fu_242_p1 = $unsigned(zext_ln27_1_fu_242_p0);

assign zext_ln27_fu_238_p0 = grp_fu_268_p3;

assign zext_ln27_fu_238_p1 = $unsigned(zext_ln27_fu_238_p0);

assign zext_ln33_fu_264_p1 = $unsigned(add_ln33_reg_385_pp0_iter3_reg);

endmodule //matprod_matprod_Pipeline_VITIS_LOOP_26_1
