// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matprod_matprod,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.600000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=3126,HLS_SYN_LUT=3716,HLS_VERSION=2022_2}" *)

module matprod (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_BUS1_AWVALID,
        s_axi_BUS1_AWREADY,
        s_axi_BUS1_AWADDR,
        s_axi_BUS1_WVALID,
        s_axi_BUS1_WREADY,
        s_axi_BUS1_WDATA,
        s_axi_BUS1_WSTRB,
        s_axi_BUS1_ARVALID,
        s_axi_BUS1_ARREADY,
        s_axi_BUS1_ARADDR,
        s_axi_BUS1_RVALID,
        s_axi_BUS1_RREADY,
        s_axi_BUS1_RDATA,
        s_axi_BUS1_RRESP,
        s_axi_BUS1_BVALID,
        s_axi_BUS1_BREADY,
        s_axi_BUS1_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;
parameter    C_S_AXI_BUS1_DATA_WIDTH = 32;
parameter    C_S_AXI_BUS1_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_BUS1_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_BUS1_AWVALID;
output   s_axi_BUS1_AWREADY;
input  [C_S_AXI_BUS1_ADDR_WIDTH - 1:0] s_axi_BUS1_AWADDR;
input   s_axi_BUS1_WVALID;
output   s_axi_BUS1_WREADY;
input  [C_S_AXI_BUS1_DATA_WIDTH - 1:0] s_axi_BUS1_WDATA;
input  [C_S_AXI_BUS1_WSTRB_WIDTH - 1:0] s_axi_BUS1_WSTRB;
input   s_axi_BUS1_ARVALID;
output   s_axi_BUS1_ARREADY;
input  [C_S_AXI_BUS1_ADDR_WIDTH - 1:0] s_axi_BUS1_ARADDR;
output   s_axi_BUS1_RVALID;
input   s_axi_BUS1_RREADY;
output  [C_S_AXI_BUS1_DATA_WIDTH - 1:0] s_axi_BUS1_RDATA;
output  [1:0] s_axi_BUS1_RRESP;
output   s_axi_BUS1_BVALID;
input   s_axi_BUS1_BREADY;
output  [1:0] s_axi_BUS1_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] m1;
wire   [63:0] m2;
wire   [63:0] m3;
wire  signed [31:0] N1;
wire  signed [31:0] N2;
wire   [31:0] N3;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state11;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state21;
reg   [0:0] icmp_ln40_reg_380;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state28;
reg   [31:0] N3_read_reg_293;
reg   [31:0] N2_read_reg_300;
reg   [31:0] N1_read_reg_306;
reg   [63:0] m3_read_reg_312;
reg   [63:0] m2_read_reg_317;
wire   [9:0] trunc_ln6_fu_194_p1;
reg   [9:0] trunc_ln6_reg_322;
wire   [9:0] trunc_ln6_1_fu_198_p1;
reg   [9:0] trunc_ln6_1_reg_327;
wire   [31:0] mul_ln23_fu_202_p2;
reg   [31:0] mul_ln23_reg_332;
wire   [0:0] icmp_ln23_fu_208_p2;
reg   [0:0] icmp_ln23_reg_338;
reg   [61:0] p_cast_reg_342;
wire   [31:0] mul_ln24_fu_234_p2;
reg   [31:0] mul_ln24_reg_353;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln24_fu_238_p2;
reg   [0:0] icmp_ln24_reg_359;
reg   [61:0] p_cast1_reg_363;
wire   [31:0] mul_ln40_fu_263_p2;
reg   [31:0] mul_ln40_reg_374;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln40_fu_267_p2;
wire  signed [61:0] p_cast3_fu_273_p4;
reg   [61:0] p_cast3_reg_384;
reg   [9:0] m1_buffer_address0;
reg    m1_buffer_ce0;
reg    m1_buffer_we0;
wire   [31:0] m1_buffer_q0;
reg   [9:0] m2_buffer_address0;
reg    m2_buffer_ce0;
reg    m2_buffer_we0;
wire   [31:0] m2_buffer_q0;
reg   [9:0] m3_buffer_address0;
reg    m3_buffer_ce0;
reg    m3_buffer_we0;
wire   [31:0] m3_buffer_q0;
wire    grp_matprod_Pipeline_1_fu_153_ap_start;
wire    grp_matprod_Pipeline_1_fu_153_ap_done;
wire    grp_matprod_Pipeline_1_fu_153_ap_idle;
wire    grp_matprod_Pipeline_1_fu_153_ap_ready;
wire    grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWVALID;
wire   [63:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWADDR;
wire   [0:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWID;
wire   [31:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWLEN;
wire   [2:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWSIZE;
wire   [1:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWBURST;
wire   [1:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWLOCK;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWCACHE;
wire   [2:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWPROT;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWQOS;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWREGION;
wire   [0:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWUSER;
wire    grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WVALID;
wire   [31:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WDATA;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WSTRB;
wire    grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WLAST;
wire   [0:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WID;
wire   [0:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WUSER;
wire    grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARVALID;
wire   [63:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARADDR;
wire   [0:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARID;
wire   [31:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARLEN;
wire   [2:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARSIZE;
wire   [1:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARBURST;
wire   [1:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARLOCK;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARCACHE;
wire   [2:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARPROT;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARQOS;
wire   [3:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARREGION;
wire   [0:0] grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARUSER;
wire    grp_matprod_Pipeline_1_fu_153_m_axi_gmem_RREADY;
wire    grp_matprod_Pipeline_1_fu_153_m_axi_gmem_BREADY;
wire   [9:0] grp_matprod_Pipeline_1_fu_153_m1_buffer_address0;
wire    grp_matprod_Pipeline_1_fu_153_m1_buffer_ce0;
wire    grp_matprod_Pipeline_1_fu_153_m1_buffer_we0;
wire   [31:0] grp_matprod_Pipeline_1_fu_153_m1_buffer_d0;
wire    grp_matprod_Pipeline_2_fu_162_ap_start;
wire    grp_matprod_Pipeline_2_fu_162_ap_done;
wire    grp_matprod_Pipeline_2_fu_162_ap_idle;
wire    grp_matprod_Pipeline_2_fu_162_ap_ready;
wire    grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWVALID;
wire   [63:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWADDR;
wire   [0:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWID;
wire   [31:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWLEN;
wire   [2:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWSIZE;
wire   [1:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWBURST;
wire   [1:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWLOCK;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWCACHE;
wire   [2:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWPROT;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWQOS;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWREGION;
wire   [0:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWUSER;
wire    grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WVALID;
wire   [31:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WDATA;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WSTRB;
wire    grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WLAST;
wire   [0:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WID;
wire   [0:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WUSER;
wire    grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARVALID;
wire   [63:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARADDR;
wire   [0:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARID;
wire   [31:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARLEN;
wire   [2:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARSIZE;
wire   [1:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARBURST;
wire   [1:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARLOCK;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARCACHE;
wire   [2:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARPROT;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARQOS;
wire   [3:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARREGION;
wire   [0:0] grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARUSER;
wire    grp_matprod_Pipeline_2_fu_162_m_axi_gmem_RREADY;
wire    grp_matprod_Pipeline_2_fu_162_m_axi_gmem_BREADY;
wire   [9:0] grp_matprod_Pipeline_2_fu_162_m2_buffer_address0;
wire    grp_matprod_Pipeline_2_fu_162_m2_buffer_ce0;
wire    grp_matprod_Pipeline_2_fu_162_m2_buffer_we0;
wire   [31:0] grp_matprod_Pipeline_2_fu_162_m2_buffer_d0;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_idle;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_ready;
wire   [9:0] grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m1_buffer_address0;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m1_buffer_ce0;
wire   [9:0] grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m2_buffer_address0;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m2_buffer_ce0;
wire   [9:0] grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_address0;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_ce0;
wire    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_we0;
wire   [31:0] grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_d0;
wire    grp_matprod_Pipeline_4_fu_185_ap_start;
wire    grp_matprod_Pipeline_4_fu_185_ap_done;
wire    grp_matprod_Pipeline_4_fu_185_ap_idle;
wire    grp_matprod_Pipeline_4_fu_185_ap_ready;
wire    grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWVALID;
wire   [63:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWADDR;
wire   [0:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWID;
wire   [31:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWLEN;
wire   [2:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWSIZE;
wire   [1:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWBURST;
wire   [1:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWLOCK;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWCACHE;
wire   [2:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWPROT;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWQOS;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWREGION;
wire   [0:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWUSER;
wire    grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WVALID;
wire   [31:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WDATA;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WSTRB;
wire    grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WLAST;
wire   [0:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WID;
wire   [0:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WUSER;
wire    grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARVALID;
wire   [63:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARADDR;
wire   [0:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARID;
wire   [31:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARLEN;
wire   [2:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARSIZE;
wire   [1:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARBURST;
wire   [1:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARLOCK;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARCACHE;
wire   [2:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARPROT;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARQOS;
wire   [3:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARREGION;
wire   [0:0] grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARUSER;
wire    grp_matprod_Pipeline_4_fu_185_m_axi_gmem_RREADY;
wire    grp_matprod_Pipeline_4_fu_185_m_axi_gmem_BREADY;
wire   [9:0] grp_matprod_Pipeline_4_fu_185_m3_buffer_address0;
wire    grp_matprod_Pipeline_4_fu_185_m3_buffer_ce0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_matprod_Pipeline_1_fu_153_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [27:0] ap_NS_fsm;
wire    ap_NS_fsm_state9;
wire    ap_CS_fsm_state9;
reg    grp_matprod_Pipeline_2_fu_162_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_NS_fsm_state18;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start_reg;
wire    ap_NS_fsm_state20;
reg    ap_block_state21_io;
reg    grp_matprod_Pipeline_4_fu_185_ap_start_reg;
wire    ap_NS_fsm_state22;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire  signed [63:0] p_cast_cast_fu_224_p1;
wire  signed [63:0] p_cast1_cast_fu_253_p1;
wire  signed [63:0] p_cast3_cast_fu_282_p1;
reg    ap_block_state28;
wire  signed [31:0] trunc_ln6_fu_194_p0;
wire  signed [31:0] trunc_ln6_1_fu_198_p0;
reg    ap_block_state10_on_subcall_done;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_block_state19_on_subcall_done;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 grp_matprod_Pipeline_1_fu_153_ap_start_reg = 1'b0;
#0 grp_matprod_Pipeline_2_fu_162_ap_start_reg = 1'b0;
#0 grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start_reg = 1'b0;
#0 grp_matprod_Pipeline_4_fu_185_ap_start_reg = 1'b0;
end

matprod_m1_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
m1_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m1_buffer_address0),
    .ce0(m1_buffer_ce0),
    .we0(m1_buffer_we0),
    .d0(grp_matprod_Pipeline_1_fu_153_m1_buffer_d0),
    .q0(m1_buffer_q0)
);

matprod_m1_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
m2_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m2_buffer_address0),
    .ce0(m2_buffer_ce0),
    .we0(m2_buffer_we0),
    .d0(grp_matprod_Pipeline_2_fu_162_m2_buffer_d0),
    .q0(m2_buffer_q0)
);

matprod_m1_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
m3_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(m3_buffer_address0),
    .ce0(m3_buffer_ce0),
    .we0(m3_buffer_we0),
    .d0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_d0),
    .q0(m3_buffer_q0)
);

matprod_matprod_Pipeline_1 grp_matprod_Pipeline_1_fu_153(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matprod_Pipeline_1_fu_153_ap_start),
    .ap_done(grp_matprod_Pipeline_1_fu_153_ap_done),
    .ap_idle(grp_matprod_Pipeline_1_fu_153_ap_idle),
    .ap_ready(grp_matprod_Pipeline_1_fu_153_ap_ready),
    .m_axi_gmem_AWVALID(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_matprod_Pipeline_1_fu_153_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .p_cast_cast(p_cast_reg_342),
    .m1_buffer_address0(grp_matprod_Pipeline_1_fu_153_m1_buffer_address0),
    .m1_buffer_ce0(grp_matprod_Pipeline_1_fu_153_m1_buffer_ce0),
    .m1_buffer_we0(grp_matprod_Pipeline_1_fu_153_m1_buffer_we0),
    .m1_buffer_d0(grp_matprod_Pipeline_1_fu_153_m1_buffer_d0),
    .sext_ln23(mul_ln23_reg_332)
);

matprod_matprod_Pipeline_2 grp_matprod_Pipeline_2_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matprod_Pipeline_2_fu_162_ap_start),
    .ap_done(grp_matprod_Pipeline_2_fu_162_ap_done),
    .ap_idle(grp_matprod_Pipeline_2_fu_162_ap_idle),
    .ap_ready(grp_matprod_Pipeline_2_fu_162_ap_ready),
    .m_axi_gmem_AWVALID(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_matprod_Pipeline_2_fu_162_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .p_cast1_cast(p_cast1_reg_363),
    .m2_buffer_address0(grp_matprod_Pipeline_2_fu_162_m2_buffer_address0),
    .m2_buffer_ce0(grp_matprod_Pipeline_2_fu_162_m2_buffer_ce0),
    .m2_buffer_we0(grp_matprod_Pipeline_2_fu_162_m2_buffer_we0),
    .m2_buffer_d0(grp_matprod_Pipeline_2_fu_162_m2_buffer_d0),
    .sext_ln24(mul_ln24_reg_353)
);

matprod_matprod_Pipeline_VITIS_LOOP_26_1 grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start),
    .ap_done(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done),
    .ap_idle(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_idle),
    .ap_ready(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_ready),
    .N1(N1_read_reg_306),
    .trunc_ln6_1(trunc_ln6_1_reg_327),
    .m1_buffer_address0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m1_buffer_address0),
    .m1_buffer_ce0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m1_buffer_ce0),
    .m1_buffer_q0(m1_buffer_q0),
    .trunc_ln6(trunc_ln6_reg_322),
    .m2_buffer_address0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m2_buffer_address0),
    .m2_buffer_ce0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m2_buffer_ce0),
    .m2_buffer_q0(m2_buffer_q0),
    .N2(N2_read_reg_300),
    .m3_buffer_address0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_address0),
    .m3_buffer_ce0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_ce0),
    .m3_buffer_we0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_we0),
    .m3_buffer_d0(grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_d0),
    .N3(N3_read_reg_293)
);

matprod_matprod_Pipeline_4 grp_matprod_Pipeline_4_fu_185(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matprod_Pipeline_4_fu_185_ap_start),
    .ap_done(grp_matprod_Pipeline_4_fu_185_ap_done),
    .ap_idle(grp_matprod_Pipeline_4_fu_185_ap_idle),
    .ap_ready(grp_matprod_Pipeline_4_fu_185_ap_ready),
    .m_axi_gmem_AWVALID(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .p_cast3_cast(p_cast3_reg_384),
    .m3_buffer_address0(grp_matprod_Pipeline_4_fu_185_m3_buffer_address0),
    .m3_buffer_ce0(grp_matprod_Pipeline_4_fu_185_m3_buffer_ce0),
    .m3_buffer_q0(m3_buffer_q0),
    .sext_ln40(mul_ln40_reg_374)
);

matprod_BUS1_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BUS1_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BUS1_DATA_WIDTH ))
BUS1_s_axi_U(
    .AWVALID(s_axi_BUS1_AWVALID),
    .AWREADY(s_axi_BUS1_AWREADY),
    .AWADDR(s_axi_BUS1_AWADDR),
    .WVALID(s_axi_BUS1_WVALID),
    .WREADY(s_axi_BUS1_WREADY),
    .WDATA(s_axi_BUS1_WDATA),
    .WSTRB(s_axi_BUS1_WSTRB),
    .ARVALID(s_axi_BUS1_ARVALID),
    .ARREADY(s_axi_BUS1_ARREADY),
    .ARADDR(s_axi_BUS1_ARADDR),
    .RVALID(s_axi_BUS1_RVALID),
    .RREADY(s_axi_BUS1_RREADY),
    .RDATA(s_axi_BUS1_RDATA),
    .RRESP(s_axi_BUS1_RRESP),
    .BVALID(s_axi_BUS1_BVALID),
    .BREADY(s_axi_BUS1_BREADY),
    .BRESP(s_axi_BUS1_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .m1(m1),
    .m2(m2),
    .m3(m3),
    .N1(N1),
    .N2(N2),
    .N3(N3),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

matprod_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWLEN(gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WDATA),
    .I_WSTRB(grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

matprod_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U30(
    .din0(N2),
    .din1(N1),
    .dout(mul_ln23_fu_202_p2)
);

matprod_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U31(
    .din0(N3_read_reg_293),
    .din1(N2_read_reg_300),
    .dout(mul_ln24_fu_234_p2)
);

matprod_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U32(
    .din0(N3_read_reg_293),
    .din1(N1_read_reg_306),
    .dout(mul_ln40_fu_263_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matprod_Pipeline_1_fu_153_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state9) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_matprod_Pipeline_1_fu_153_ap_start_reg <= 1'b1;
        end else if ((grp_matprod_Pipeline_1_fu_153_ap_ready == 1'b1)) begin
            grp_matprod_Pipeline_1_fu_153_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matprod_Pipeline_2_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state18) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_matprod_Pipeline_2_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_matprod_Pipeline_2_fu_162_ap_ready == 1'b1)) begin
            grp_matprod_Pipeline_2_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matprod_Pipeline_4_fu_185_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state22) & (1'b1 == ap_CS_fsm_state21))) begin
            grp_matprod_Pipeline_4_fu_185_ap_start_reg <= 1'b1;
        end else if ((grp_matprod_Pipeline_4_fu_185_ap_ready == 1'b1)) begin
            grp_matprod_Pipeline_4_fu_185_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state20) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start_reg <= 1'b1;
        end else if ((grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_ready == 1'b1)) begin
            grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        N1_read_reg_306 <= N1;
        N2_read_reg_300 <= N2;
        N3_read_reg_293 <= N3;
        icmp_ln23_reg_338 <= icmp_ln23_fu_208_p2;
        m2_read_reg_317 <= m2;
        m3_read_reg_312 <= m3;
        mul_ln23_reg_332 <= mul_ln23_fu_202_p2;
        trunc_ln6_1_reg_327 <= trunc_ln6_1_fu_198_p1;
        trunc_ln6_reg_322 <= trunc_ln6_fu_194_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        icmp_ln24_reg_359 <= icmp_ln24_fu_238_p2;
        mul_ln24_reg_353 <= mul_ln24_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        icmp_ln40_reg_380 <= icmp_ln40_fu_267_p2;
        mul_ln40_reg_374 <= mul_ln40_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln24_fu_238_p2 == 1'd0))) begin
        p_cast1_reg_363 <= {{m2_read_reg_317[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd0))) begin
        p_cast3_reg_384 <= {{m3_read_reg_312[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln23_fu_208_p2 == 1'd0))) begin
        p_cast_reg_342 <= {{m1[63:2]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state10_on_subcall_done)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state19_on_subcall_done)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state21_io) | (grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done == 1'b0))) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_matprod_Pipeline_4_fu_185_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

always @ (*) begin
    if (((gmem_BVALID == 1'b0) & (icmp_ln40_reg_380 == 1'd0))) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((~((gmem_BVALID == 1'b0) & (icmp_ln40_reg_380 == 1'd0)) & (1'b1 == ap_CS_fsm_state28))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_BVALID == 1'b0) & (icmp_ln40_reg_380 == 1'd0)) & (1'b1 == ap_CS_fsm_state28))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        gmem_ARADDR = p_cast1_cast_fu_253_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARADDR = p_cast_cast_fu_224_p1;
    end else if (((1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0)))) begin
        gmem_ARADDR = grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0)))) begin
        gmem_ARADDR = grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        gmem_ARLEN = mul_ln24_reg_353;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARLEN = mul_ln23_reg_332;
    end else if (((1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0)))) begin
        gmem_ARLEN = grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0)))) begin
        gmem_ARLEN = grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0)))) begin
        gmem_ARVALID = grp_matprod_Pipeline_2_fu_162_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0)))) begin
        gmem_ARVALID = grp_matprod_Pipeline_1_fu_153_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21_io) | (grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd0))) begin
        gmem_AWADDR = p_cast3_cast_fu_282_p1;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_AWADDR = grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21_io) | (grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd0))) begin
        gmem_AWLEN = mul_ln40_reg_374;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_AWLEN = grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state21_io) | (grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd0))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_AWVALID = grp_matprod_Pipeline_4_fu_185_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_BVALID == 1'b0) & (icmp_ln40_reg_380 == 1'd0)) & (1'b1 == ap_CS_fsm_state28) & (icmp_ln40_reg_380 == 1'd0))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_BREADY = grp_matprod_Pipeline_4_fu_185_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0)))) begin
        gmem_RREADY = grp_matprod_Pipeline_2_fu_162_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0)))) begin
        gmem_RREADY = grp_matprod_Pipeline_1_fu_153_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_WVALID = grp_matprod_Pipeline_4_fu_185_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd0))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) & (icmp_ln40_reg_380 == 1'd0))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        m1_buffer_address0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m1_buffer_address0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0))) begin
        m1_buffer_address0 = grp_matprod_Pipeline_1_fu_153_m1_buffer_address0;
    end else begin
        m1_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        m1_buffer_ce0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m1_buffer_ce0;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0))) begin
        m1_buffer_ce0 = grp_matprod_Pipeline_1_fu_153_m1_buffer_ce0;
    end else begin
        m1_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln23_reg_338 == 1'd0))) begin
        m1_buffer_we0 = grp_matprod_Pipeline_1_fu_153_m1_buffer_we0;
    end else begin
        m1_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        m2_buffer_address0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m2_buffer_address0;
    end else if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0))) begin
        m2_buffer_address0 = grp_matprod_Pipeline_2_fu_162_m2_buffer_address0;
    end else begin
        m2_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        m2_buffer_ce0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m2_buffer_ce0;
    end else if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0))) begin
        m2_buffer_ce0 = grp_matprod_Pipeline_2_fu_162_m2_buffer_ce0;
    end else begin
        m2_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (icmp_ln24_reg_359 == 1'd0))) begin
        m2_buffer_we0 = grp_matprod_Pipeline_2_fu_162_m2_buffer_we0;
    end else begin
        m2_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        m3_buffer_address0 = grp_matprod_Pipeline_4_fu_185_m3_buffer_address0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        m3_buffer_address0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_address0;
    end else begin
        m3_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        m3_buffer_ce0 = grp_matprod_Pipeline_4_fu_185_m3_buffer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        m3_buffer_ce0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_ce0;
    end else begin
        m3_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        m3_buffer_we0 = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_m3_buffer_we0;
    end else begin
        m3_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln23_fu_208_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln23_fu_208_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln24_fu_238_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln24_fu_238_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((1'b0 == ap_block_state19_on_subcall_done) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if ((~((1'b1 == ap_block_state21_io) | (grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if ((~((1'b1 == ap_block_state21_io) | (grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state21) & (icmp_ln40_reg_380 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_matprod_Pipeline_4_fu_185_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if ((~((gmem_BVALID == 1'b0) & (icmp_ln40_reg_380 == 1'd0)) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state18 = ap_NS_fsm[32'd17];

assign ap_NS_fsm_state20 = ap_NS_fsm[32'd19];

assign ap_NS_fsm_state22 = ap_NS_fsm[32'd21];

assign ap_NS_fsm_state9 = ap_NS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_matprod_Pipeline_1_fu_153_ap_done == 1'b0) & (icmp_ln23_reg_338 == 1'd0));
end

always @ (*) begin
    ap_block_state19_on_subcall_done = ((grp_matprod_Pipeline_2_fu_162_ap_done == 1'b0) & (icmp_ln24_reg_359 == 1'd0));
end

always @ (*) begin
    ap_block_state21_io = ((gmem_AWREADY == 1'b0) & (icmp_ln40_reg_380 == 1'd0));
end

always @ (*) begin
    ap_block_state28 = ((gmem_BVALID == 1'b0) & (icmp_ln40_reg_380 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_matprod_Pipeline_1_fu_153_ap_start = grp_matprod_Pipeline_1_fu_153_ap_start_reg;

assign grp_matprod_Pipeline_2_fu_162_ap_start = grp_matprod_Pipeline_2_fu_162_ap_start_reg;

assign grp_matprod_Pipeline_4_fu_185_ap_start = grp_matprod_Pipeline_4_fu_185_ap_start_reg;

assign grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start = grp_matprod_Pipeline_VITIS_LOOP_26_1_fu_171_ap_start_reg;

assign icmp_ln23_fu_208_p2 = ((mul_ln23_fu_202_p2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_238_p2 = ((mul_ln24_fu_234_p2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_267_p2 = ((mul_ln40_fu_263_p2 == 32'd0) ? 1'b1 : 1'b0);

assign p_cast1_cast_fu_253_p1 = $signed(p_cast1_reg_363);

assign p_cast3_cast_fu_282_p1 = p_cast3_fu_273_p4;

assign p_cast3_fu_273_p4 = {{m3_read_reg_312[63:2]}};

assign p_cast_cast_fu_224_p1 = $signed(p_cast_reg_342);

assign trunc_ln6_1_fu_198_p0 = N2;

assign trunc_ln6_1_fu_198_p1 = trunc_ln6_1_fu_198_p0[9:0];

assign trunc_ln6_fu_194_p0 = N3;

assign trunc_ln6_fu_194_p1 = trunc_ln6_fu_194_p0[9:0];

endmodule //matprod
