# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/project_1/project_1.srcs/sources_1/bd/accel/ip/accel_matprod_0_3/accel_matprod_0_3.xci
# IP: The module: 'accel_matprod_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/project_1/project_1.gen/sources_1/bd/accel/ip/accel_matprod_0_3/constraints/matprod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accel_matprod_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/project_1/project_1.srcs/sources_1/bd/accel/ip/accel_matprod_0_3/accel_matprod_0_3.xci
# IP: The module: 'accel_matprod_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/project_1/project_1.gen/sources_1/bd/accel/ip/accel_matprod_0_3/constraints/matprod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'accel_matprod_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
