# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/rvfpga/rvfpga.srcs/sources_1/bd/interconnect/ip/interconnect_auto_ds_0/interconnect_auto_ds_0.xci
# IP: The module: 'interconnect_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/rvfpga/rvfpga.gen/sources_1/bd/interconnect/ip/interconnect_auto_ds_0/interconnect_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/rvfpga/rvfpga.gen/sources_1/bd/interconnect/ip/interconnect_auto_ds_0/interconnect_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/rvfpga/rvfpga.srcs/sources_1/bd/interconnect/ip/interconnect_auto_ds_0/interconnect_auto_ds_0.xci
# IP: The module: 'interconnect_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/rvfpga/rvfpga.gen/sources_1/bd/interconnect/ip/interconnect_auto_ds_0/interconnect_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/catia/Rui/MSc_Dissertation/SoC/RVfpgaXilinxIntercon/rvfpga/rvfpga.gen/sources_1/bd/interconnect/ip/interconnect_auto_ds_0/interconnect_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interconnect_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
