# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/rvfpganexys.xdc

# XDC: imports/src/LiteDRAM/liteDRAM.xdc

# Block Designs: bd/interconnect/interconnect.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interconnect || ORIG_REF_NAME==interconnect} -quiet] -quiet

# IP: bd/interconnect/ip/interconnect_xbar_0/interconnect_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interconnect_xbar_0 || ORIG_REF_NAME==interconnect_xbar_0} -quiet] -quiet

# IP: bd/interconnect/ip/interconnect_s00_data_fifo_0/interconnect_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interconnect_s00_data_fifo_0 || ORIG_REF_NAME==interconnect_s00_data_fifo_0} -quiet] -quiet

# IP: bd/interconnect/ip/interconnect_s01_data_fifo_0/interconnect_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interconnect_s01_data_fifo_0 || ORIG_REF_NAME==interconnect_s01_data_fifo_0} -quiet] -quiet

# IP: bd/interconnect/ip/interconnect_s02_data_fifo_0/interconnect_s02_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interconnect_s02_data_fifo_0 || ORIG_REF_NAME==interconnect_s02_data_fifo_0} -quiet] -quiet

# IP: bd/interconnect/ip/interconnect_axi_interconnect_0_0/interconnect_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==interconnect_axi_interconnect_0_0 || ORIG_REF_NAME==interconnect_axi_interconnect_0_0} -quiet] -quiet

# XDC: c:/Users/Rui/Rui/MSc_Dissertation/SoC/RVfpga_/rvfpga/rvfpga.gen/sources_1/bd/interconnect/interconnect_ooc.xdc
